# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  #- "rules/myrule.yml"
  - "rules/linuxrules.yml"
  #- "rules/windowsrules.yml"
  #- "rules/webrules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["34.89.211.184:9090"]
        # scraping from https /metrics
    scheme: https
    tls_config:
      ca_file:  web_config/tls/prometheus.crt
      #insecure_skip_verify: true
    basic_auth:
      username: admin
      password: admin


  - job_name: "node_exporter"
    #static_configs:
    #  - targets: ["34.89.211.184:9100"]
    # all the changes in file_sd.yml are dynamically applied and there is no need for kill -HUP
    file_sd_configs:
      - files:
        - file_sd.yml

  - job_name: "alertmanager"
    static_configs:
      - targets: ["34.89.211.184:9093"]

# Exporter itself
  - job_name: "blackbox_exporter"
    static_configs:
      - targets: ["34.89.211.184:9115"]
  
  - job_name: "grafana"
    static_configs:
      - targets: ["34.89.211.184:3000"]

  - job_name: "prometheus_website"
    static_configs:
      - targets:
        - prometheus.io
    metrics_path: /probe
    params: 
      module: 
        - http_ipv4
        ## relabeling
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 34.89.211.184:9115  # The blackbox exporter's real hostname:port.

  - job_name: "pushgateway"
  #demo_metric{event="add", exported_instance="demo_instance", exported_job="demo_pg_job", instance="34.89.211.184:9091", job="pushgateway"}
  #To delete push gateway labels we use honor_labels:true - instance="34.89.211.184:9091", job="pushgateway"
  #so we have: demo_metric{event="add", instance="demo_instance", job="demo_pg_job"}
    honor_labels: true
    static_configs:
      - targets: ["34.89.211.184:9091"]



# API HTTP ENDPOINTS FOR QUERY:
# https://34.89.211.184:9090/api/v1/query?query=up this is api enpoint for quering up
# https://34.89.211.184:9090/api/v1/targets
